KPITV/src/KPITV/Controllers/StuffController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using KPITV.Models.StuffViewModels;
using KPITV.Models;
using KPITV.Models.Data;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using KPITV.Models.BusinessLogic;
using Microsoft.EntityFrameworkCore;

namespace KPITV.Controllers
{
    public class StuffController : Controller
    {
        ApplicationDbContext db;
        UserManager<ApplicationUser> userManager;
        IHostingEnvironment hostingEnvironment;

        public StuffController(ApplicationDbContext db, UserManager<ApplicationUser> userManager, IHostingEnvironment hostingEnvironment)
        {
            this.db = db;
            this.userManager = userManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        [Route("[controller]")]
        public IActionResult Index()
        {
            var types = db.Stuff.Select(a => a.Type).ToList().Distinct();
            return View(types);
        }

        [Route("[controller]/{type}")]
        public IActionResult Type(string type)
        {
            var items = db.Stuff.Where(a => a.Type == type).ToList();
            return View(items);
        }

        [Route("[controller]/{type}/{number}")]
        public IActionResult Item(string type, string number)
        {
            var stuffItem = db.Stuff.Where(a => a.Number == number).Include(a => a.Owner).FirstOrDefault();
            return View(stuffItem);
        }

        [Route("[controller]/[action]")]
        public async Task<IActionResult> Add()
        {
            List<StuffViewModel.Owner> owners = new List<StuffViewModel.Owner>();
            var members = await userManager.GetUsersInRoleAsync("Member") as List<ApplicationUser>;
            foreach (var item in members)
                owners.Add(new StuffViewModel.Owner
                {
                    OwnerName = $"{item.FirstName} {item.LastName}",
                    ImageLink = item.ImageLink,
                    ProfileLink = item.ProfileLink
                });
            var otherOwners = db.Stuff.Select(a => a.OwnerName).Distinct().ToList();
            foreach (var item in otherOwners)
                if (owners.Count(a => a.OwnerName == item) == 0)
                    owners.Add(new StuffViewModel.Owner
                    {
                        OwnerName = item,
                        ImageLink = "images/profile_photos/default.jpg",
                        ProfileLink = ""
                    });
            StuffViewModel svm = new StuffViewModel()
            {
                Types = db.Stuff.Select(a => a.Type).Distinct().ToList(),
                Members = owners
            };
            return View(svm);
        }

        [Route("[controller]/[action]")]
        [HttpPost]
        public async Task<IActionResult> Add(string name, string type, string number, string description, string owner, IFormFile photo)
        {
            Stuff stuff = new Stuff()
            {
                Name = name,
                Type = type,
                Number = number,
                Description = description,
                ImageLink = photo != null ? await StuffHelper.AddPhoto(name, type, photo) : "wwwroot/images/stuff/default.png",
            };
            var user = userManager.FindByProfileLink(db, owner);
            if (user != null)
            {
                stuff.OwnerId = user.Id;
                stuff.OwnerName = $"{user.FirstName} {user.LastName}";
            }
            else
                stuff.OwnerName = owner;
            db.Stuff.Add(stuff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult CheckNumber(string number)
        {
            if (db.Stuff.Count(a => a.Number == number) > 0)
                return Json(false);
            else
                return Json(true);
        }

        public IActionResult CheckType(string type)
        {
            if (db.Stuff.Count(a => a.Type.ToUpper() == type.ToUpper()) > 0)
                return Json(false);
            else
                return Json(true);
        }

        public IActionResult CheckOwnerName(string name)
        {
            if (db.Users.Count(a => $"{a.FirstName} {a.LastName}" == name) > 0)
                return Json(false);
            else
                return Json(true);
        }
    }
}

KPITV/src/KPITV/Controllers/UsersController.cs
using KPITV.Models;
using KPITV.Models.Data;
using KPITV.Models.UsersViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace KPITV.Controllers
{
    [Authorize(Roles = "Admin,Moderator")]
    public class UsersController : Controller
    {
        ApplicationDbContext db;
        readonly UserManager<ApplicationUser> userManager;

        public UsersController(UserManager<ApplicationUser> userManager, ApplicationDbContext db)
        {
            this.userManager = userManager;
            this.db = db;
        }

        [Route("users")]
        public async Task<IActionResult> Index()
        {
            Dictionary<ApplicationUser, List<string>> usersDict = new Dictionary<ApplicationUser, List<string>>();
            var users = await userManager.GetUsersInRoleAsync("Member");
            foreach (var user in users)
            {
                usersDict.Add(user, await userManager.GetRolesAsync(user) as List<string>);
            }
            return View(new UsersViewModel { Users = usersDict });
        }

        [HttpPost]
        public async Task<IActionResult> ChangeRole(string name, string role, bool hasRole)
        {
            if (hasRole)
                await userManager.AddToRoleAsync(await userManager.FindByNameAsync(name), role);
            else
            {
                var lol = await userManager.FindByNameAsync(name);
                await userManager.RemoveFromRoleAsync(await userManager.FindByNameAsync(name), role);
            }
            db.SaveChanges();
            return new EmptyResult();
        }
    }
}

KPITV/src/KPITV/Views/Shared/_Layout.cshtml
@inject UserManager<ApplicationUser> UserManager
@using System.Collections.Generic

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] KPITV</title>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
</head>
<body>
    <div class="loading-animation"></div>
    <nav class="navbar navbar-default">
        <a class="navbar-brand logo-brand" href="#"></a>
        <ul class="nav navbar-nav">
            <li><a href="@Url.Action("Index", "Home")">Home</a></li>
            <li><a href="@Url.Action("Index", "Stuff")">Stuff</a></li>
            @if (User.IsInRole("Moderator") || User.IsInRole("Admin"))
            {
                <li><a href="@Url.Action("Index", "Users")">Users</a></li>
            }
        </ul>
        <ul class="nav navbar-nav navbar-right user-menu">
            @await Html.PartialAsync("_LoginPartial")
        </ul>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>